Console.WriteLine("Введите координаты первой точки");
int x1 = Convert.ToInt32(Console.ReadLine());
int y1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координаты второй точки");
int x2 = Convert.ToInt32(Console.ReadLine());
int y2 = Convert.ToInt32(Console.ReadLine());
double result = Math.Sqrt(Math.Pow(x1-x2, 2)+Math.Pow(y1-y2, 2));
Console.WriteLine($"Расстояние равно {Math.Round(result, 2)}");
// double number = 25;
// Console.WriteLine(Math.Sqrt(number));
